### ISSUE TITLE
Добавить поле hostname в сортировку

### ISSUE THREAD

**Issue by Oichemhaith** [spo0okie/arms_inventory#159]
Добавить поле hostname чтобы можно было сортировку по нему делать а то по инвентарнику по порядку имена не идут
![Снимок](https://github.com/spo0okie/arms_inventory/assets/31934338/87db051d-6d7b-4efa-bbb2-9a0fcc793af0)

**Comment by spo0okie** [comment]
Если столбец hostname отображается явно (через настройки таблицы) то в столбце инвентарного номера он уже отображаться не должен. Это должно касаться также поиска и сортировки содержимого столбца инвентарный номер
