### ISSUE TITLE
Сортировка "Расход материалов"

### ISSUE THREAD

**Issue by savichev** [spo0okie/arms_inventory#19]
Требуется сделать сортировку в "Расход материалов" по дате (новые - сверху).

**Comment by savichev** [comment]
Сортировка по дате расхода, а не по фактическому вводу данных.

**Comment by spo0okie** [comment]
Короче выношу дату расхода в отдельный столбец и делаю по нему сортировку и поиск. Правильно?
Ну и наверно сразу сделать что по умолчанию отсортировано по этому полю
