### ISSUE TITLE
Идентификация подключенных хостов на микротиках.

### ISSUE THREAD

**Issue by savichev** [spo0okie/arms_inventory#21]
Делать идентификацию подключенных хостов на микротах и вносить в инвентаризацию значения их фактического расположения.

пример скрипта

```bash
# Get HostName connected clients
:if ($leaseBound = 1) do={
  :local sysname
  :set sysname [/system identity get name];
  /ip dhcp-server lease;
  :foreach i in=[find dynamic=yes] do={
    :local dhcpip
    :set dhcpip [ get $i address ];
    :local dhcphn
    :set dhcphn [get $i host-name];
    :local dhcpmac
    :set dhcpmac [get $i mac-address];
    :if ($leaseActIP = $dhcpip) do={
      :local comment "DHCP Host connected: "
      :set comment ( $comment . $dhcphn . " [" . $dhcpip . " - " . $dhcpmac . "] on " . $sysname);
      :log info ( $comment );
      :log info ( "/tool fetch host=\"inventory\" keep-result=no mode=http address=\"inventory\" src-path=\"/api/mac/$sysname/$dhcpmac\"" );
#     /tool fetch host="mysite.ru" keep-result=no mode=http address="mysite.ru" src-path="/sms.php?text=IP:$leaseActIP;$leaseActMAC;SRV:$leaseServerName;HN:$clientid"
    }
  }
}
```
Получим запрос вида
http://inventory/api/mac/CHELYABINSK/50:8F:4C:72:46:D8

P.S.
На микротиках должен быть правильно указан **system Identity**

**Comment by spo0okie** [comment]
Нужно добавить поиск оборудования по MAC и поиск помещения первого уровня из любого помещения

**Comment by savichev** [comment]
Пример скрипта, который собирает маки и хостнэймы подключившихся устройств и получивших аренду от dhcp сервера

:if ($leaseBound = 1) do={
 /ip dhcp-server lease;
 :foreach i in=[find dynamic=yes address=$leaseActIP] do={
    :local dhcpip [ get $i address ];
   :local dhcphn [get $i host-name];
   :local dhcpmac [get $i mac-address];
   :local comment "DHCP Host connected: $dhcphn [$dhcpip - $dhcpmac]"
   :log error $comment
   :if ([:len [/file find name=macs.txt]] > 0) do={
       /file set macs.txt contents=([get macs.txt contents] $dhcpmac . "@" . $dhcphn)
    } else={
       /file print file=macs.txt
        /file set macs.txt contents=($dhcpmac . "@" . $dhcphn)
   }
 }
}

Размещается скрипт в
DHCP Server -> DHCP -> ${NAME} -> script

**Comment by spo0okie** [comment]
чтобы не забыть: чтобы нормально работать с MAC нужно сделать строгий формат хранения МАС.
1. onBeforeSave - делать приведение к формату.
2. сделать миграцию для приведения к формату всех внесенных МАС

**Comment by spo0okie** [comment]
1 и 2 сделано. Нужен поиск оборудования по MAC

**Comment by spo0okie** [comment]
поиск по MAC сделан, теперь нужно получить ID площадки

/web/api/techs/search-by-mac?mac=00c0b7b9b028
<response>
<id>236</id>
<num>МСК-ИБП-0003</num>
<inv_num/>
<model_id>135</model_id>
<sn>AS1315243475</sn>
<arms_id/>
<places_id>12</places_id>
<user_id>0</user_id>
<it_staff_id>0</it_staff_id>
<ip>192.168.70.9</ip>
<mac>00c0b7b9b028</mac>
<state_id>5</state_id>
<url>http://192.168.70.9</url>
<comment/>
<history>Батареи заменены - 01.04.2019</history>
</response>

**Comment by spo0okie** [comment]
добавил поле-функцию site, в запросе API надо указывать expand=site
/web/api/techs/search-by-mac?mac=00c0b7b9b028&expand=site

```
<response>
<id>236</id>
<num>МСК-ИБП-0003</num>
<inv_num/>
<model_id>135</model_id>
<sn>AS1315243475</sn>
<arms_id/>
<places_id>12</places_id>
<user_id>0</user_id>
<it_staff_id>0</it_staff_id>
<ip>192.168.70.9</ip>
<mac>00c0b7b9b028</mac>
<state_id>5</state_id>
<url>http://192.168.70.9</url>
<comment/>
<history>Батареи заменены - 01.04.2019</history>
<site>
<id>1</id>
<parent_id/>
<name>Московский офис</name>
<addr>143441, Моск. обл., Красногорский р-н, п/о Путилково, 69 км МКАД, офисный комплекс ЗАО «Гринвуд», 23 стр., 6 этаж</addr>
<prefix>МСК</prefix>
<short>Москва</short>
</site>
</response>

```

**Comment by spo0okie** [comment]
собственно собрав с микрота маки и опросив инвентаризацию на предмет поиска оборудования с этим МАКом можно по полю response.site.id понять а на той ли площадке железка закреплена. ну и тригерить в нужную сторону
