### ISSUE TITLE
Cканирование документов напрямую в базу

### ISSUE THREAD

**Issue by nischebrod** [spo0okie/arms_inventory#25]
Привязка документа в одноименном разделе сейчас сопряжена с дополнительными, промежуточными действиями, Документ сначала сканируется, потом сохраняется на компьютер в промежуточную папку в виде файла в формате PDF, потом нужно нажать кнопку создать новый документ, потом подтянуть его базу. Очень рутинно и затратно по времени.
Этот процесс был бы гораздо проще, если бы для появления документа в базе данных, достаточно было бы просто отправить электронное письмо, с вложенным документом, на "специальный" почтовый ящик.
Всё, что останется, при таком подходе, это только привязать этот документ к объектам в базе.

**Comment by spo0okie** [comment]
Может надо какойто статус выставлять автозагруженным документам?

**Comment by spo0okie** [comment]
https://github.com/spo0okie/arms_mail_scans
скрипт импорта сканов в инвентаризацию
