### ISSUE TITLE
Дельта времени при отправке данных об ОСях скриптами. 

### ISSUE THREAD

**Issue by Mkl200** [spo0okie/arms_inventory#82]
Выглядит как -179 минут.

**Comment by spo0okie** [comment]
Нужно добавить выставление часового пояса соединения с БД в GMT

https://wiki.reviakin.net/%D0%B8%D0%BD%D0%B2%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F:%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0#%D0%B1%D0%B0%D0%B7%D0%B0_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85
